# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-29 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0002_auto_20161129_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suser',
            name='student_id',
        ),
    ]
