# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0002_auto_20170520_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='bachelor_major_code',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='suser',
            name='remark',
            field=models.CharField(default='', max_length=256),
        ),
    ]
