# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0003_auto_20170520_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='training_direction_code',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
