# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-30 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0003_remove_suser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='student_id',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
