# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-02 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0004_suser_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suser',
            old_name='student_id',
            new_name='username',
        ),
    ]
