# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0005_auto_20161202_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='is_sample',
            field=models.BooleanField(default=1),
        ),
    ]
