# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0006_suser_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suser',
            name='qid_list',
            field=models.TextField(default=''),
        ),
    ]
