# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0007_auto_20161221_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suser',
            name='qid_list',
            field=models.TextField(default='{}'),
        ),
    ]
