# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-18 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0010_auto_20170212_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suser',
            old_name='domitory_telephone',
            new_name='dormitory_telephone',
        ),
    ]
