# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-18 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0011_auto_20170218_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suser',
            old_name='bechelor_graduate_time',
            new_name='bachelor_graduate_time',
        ),
        migrations.RenameField(
            model_name='suser',
            old_name='bechelor_major',
            new_name='bachelor_major',
        ),
        migrations.RenameField(
            model_name='suser',
            old_name='bechelor_major_code',
            new_name='bachelor_major_code',
        ),
        migrations.RenameField(
            model_name='suser',
            old_name='bechelor_school_code',
            new_name='bachelor_school_code',
        ),
        migrations.RenameField(
            model_name='suser',
            old_name='bechelor_student_number',
            new_name='bachelor_student_number',
        ),
    ]
