# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0012_auto_20170218_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sample_list', models.TextField(default='{}')),
            ],
        ),
    ]
