# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('pswd', models.CharField(max_length=32)),
            ],
        ),
    ]
