# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=-1)),
                ('uid', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answeraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('update_time', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('answer_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('qtype', models.IntegerField()),
                ('content', models.TextField()),
                ('dependency', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('title', models.CharField(max_length=64)),
                ('founder', models.IntegerField()),
                ('question_list', models.TextField()),
                ('user_list', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
