# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-02 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answeraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('submit_time', models.DateTimeField(default='1970-01-01 00:00:00.000000')),
                ('ip', models.CharField(default='unknown', max_length=64)),
                ('agent', models.CharField(default='unknown', max_length=1024)),
                ('os', models.CharField(default='unknown', max_length=64)),
                ('answers', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default='1970-01-01 00:00:00.000000')),
                ('update_time', models.DateTimeField(default='1970-01-01 00:00:00.000000')),
                ('release_time', models.DateTimeField(default='1970-01-01 00:00:00.000000')),
                ('close_time', models.DateTimeField(default='1970-01-01 00:00:00.000000')),
                ('founder', models.IntegerField(default=-1)),
                ('title', models.CharField(default='', max_length=128)),
                ('questions', models.TextField(default='')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('title', models.TextField()),
                ('report', models.TextField()),
            ],
        ),
    ]
