# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-14 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dependency',
        ),
        migrations.AlterField(
            model_name='answer',
            name='aid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
