# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='question_list',
            field=models.TextField(default=''),
        ),
    ]
