# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-31 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='report_id',
            field=models.IntegerField(default=-1),
        ),
    ]
