# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-22 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_auto_20161214_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaire',
            name='user_list',
        ),
        migrations.AddField(
            model_name='questionaire',
            name='create_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='founder',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
