# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_auto_20161212_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
