# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_answeraire_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
