# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_auto_20161222_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='answeraire',
            name='update_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='create_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='update_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
    ]
