# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_report_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
