# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-20 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0006_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='close_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='release_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
    ]
