# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_auto_20170220_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeraire',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='answeraire',
            name='update_time',
        ),
        migrations.AddField(
            model_name='answeraire',
            name='time_consume',
            field=models.IntegerField(default=0),
        ),
    ]
